grid:
  voxel: 0.04
  size:
    - 5.12
    - 5.12
    - 1.4
  origin_w:
    - -2.56
    - -2.56
    - 0.0
  start_w:
    - 0.0
    - 0.0
    - 0.75
  goal_w:
    - 2.0
    - 0.0
    - 0.75
  axis_order: xyz
